tasks:
  - command: for i in {1..5}; do code --uninstall-extension vscjava.vscode-java-test; sleep 10; done
vscode:
 extensions:
   - redhat.java
   - vscjava.vscode-java-debug
   - revaturePro.revature-labs
